from __future__ import annotations
import re
import unicodedata
from persona_twin.schema import Turn

# Sources whose every turn is client-derived data, regardless of content.
# Currently the only Karbon export ingested is practice-management data
# (client tax files, engagement notes) — never the subject's own writing.
CONFIDENTIAL_SOURCES = {"karbon"}


def _is_confidential_source(source: str) -> bool:
    """Case- and naming-variant-tolerant match against CONFIDENTIAL_SOURCES.

    An exact, case-sensitive `in` check treats "Karbon", "KARBON" and
    "karbon_export" as ordinary open sources -- and this is the rule that
    protects records carrying NO content markers at all, so getting it
    wrong fails in the worst possible direction. No Karbon connector exists
    yet, which is exactly what makes it a trap: whoever writes one has no
    established casing or naming to match against. This codebase's own
    convention for connector names is a compound "<source>_<subtype>" (see
    git_repos, claude_ai, claude_code), so "karbon_export" is a plausible
    real name, not a hypothetical one -- matched here as a prefix, not a
    substring, so an unrelated source that merely contains "karbon"
    somewhere in its name would not.
    """
    normalized = source.strip().lower()
    return any(normalized == s or normalized.startswith(f"{s}_")
               for s in CONFIDENTIAL_SOURCES)


class ClassifyError(Exception):
    """Raised when classification cannot proceed on malformed input.

    Mirrors scrub/secrets.py's ScrubError: a classifier that crashes loudly
    on input it cannot interpret is safer than one that silently falls
    through to "open" because an unexpected type made every marker's
    .search() a no-op.
    """


# Separators: people write the same identifier several ways. The canonical
# hyphenated forms and bare digit runs were matched from the start; the
# space- and dot-separated variants were added after a review found them
# missed, at a measured cost of 3 extra turns in 81,438 (0.55% -> 0.55%).
#
# The trailing \s{0,4} tolerates a hard line-wrap landing right after the
# separator (e.g. a chat client wrapping "123-45-" onto the next line before
# "6789") -- a real separator character is still required; this only asks it
# to not also demand that no incidental whitespace follow it. Bounded at 4
# characters (covers "\r\n" plus a couple of stray indent characters from a
# paste) rather than unbounded, so this can't bridge two genuinely unrelated
# numbers separated by a blank line or more.
_SEP = r"[-. ]\s{0,4}"

# This module has now shipped the identical defect five times: a fix
# correct on one member of a word alternation, leaving a sibling member of
# the SAME alternation unguarded, across four separate review rounds
# (the "no" qualifier's short forms, then "number" itself, and along the
# way the boundary-escape fix on \d{9,} that started this whole pattern).
# Review is the wrong instrument for a property of how a table is built --
# it can only find members one at a time. So every word-alternation family
# below is defined ONCE as a plain tuple of member strings, and every
# regex fragment built from it is generated by the same helper, which
# applies the SAME trailing-letter guard to every member automatically.
# There is no path left for a new member to be added to a family without
# the guard, because there is no longer anywhere to write a member without
# also going through this function -- and test_classify.py's structural
# invariant test (test_every_qualifier_and_noun_member_rejects_a_trailing_letter)
# imports these same tuples, so it automatically covers a member added
# here without the test itself being edited.
def _guarded_alternation(words: tuple[str, ...]) -> str:
    """Build `(?:w1\\.?|w2\\.?|...)(?![a-zA-Z])` from `words`.

    The trailing negative lookahead rejects a letter glued directly onto
    any member (the prefix-swallowing case: "no" inside "notes", "number"
    inside "numbering", "acct" inside... nothing, coincidentally, but the
    guard costs nothing to apply uniformly and there is no way to know in
    advance which future member will turn out to be a real English or
    domain-word prefix). It does NOT reject a member followed by a space,
    digit, punctuation, or end of string -- "acct no. 12345678" and "the
    account no longer has any activity" (a standalone "no" followed by a
    space, not a letter) both still match; only the avoidable, glued-on
    case is closed.
    """
    body = "|".join(rf"{re.escape(w)}\.?" for w in words)
    return rf"(?:{body})(?![a-zA-Z])"


# The qualifier family that can follow "routing" / "aba" / "account" /
# "acct" / "a/c": a bare "#", or one of these words. A review found the
# phrase marker caught "account number" and "account #" but missed "acct
# no. 12345678", "account no 12345678" and "acct num 12345678", each a
# different spelling of the same qualifier, not a different marker.
_QUALIFIER_WORDS = ("number", "nbr", "num", "no")
_QUALIFIER = rf"(?:{_guarded_alternation(_QUALIFIER_WORDS)}|#)"

# Routing and ABA are the same concept under two names -- ABA (American
# Bankers Association) routing numbers are commonly called "ABA number" or
# "ABA #" without ever using the word "routing" at all.
_ROUTING_NOUN_WORDS = ("routing", "aba")
_ACCOUNT_NOUN_WORDS = ("account", "acct", "a/c")
_ROUTING_NOUN = _guarded_alternation(_ROUTING_NOUN_WORDS)
_ACCOUNT_NOUN = _guarded_alternation(_ACCOUNT_NOUN_WORDS)

# A noun connected DIRECTLY to a bare number, with a colon or nothing at all
# between them and no qualifier word required: "acct: 12345678", "account:
# 12345678", "bank acct 12345678". Deliberately narrow and measured, not a
# general connector sweep -- a colon and plain whitespace are the two cheap,
# zero-risk cases; a slash was considered and rejected (zero corpus
# exposure, and it risks matching ordinary date shapes like "acct/2026"),
# and "ending in NNNN" last-4-digit disclosure was considered and rejected
# (23 turns, and the review that found it declined to recommend closing it).
# \d{4,} is deliberately much lower than the bare-digit-run marker's 9-digit
# floor: an explicit noun immediately before the number is already doing
# the discriminating work a bare digit run can't, so a short account number
# doesn't need the same protection against ordinary dates/phone numbers
# that justifies the higher floor elsewhere in this module.
#
# No trailing \b after \d{4,}: found, on building the boundary-uniformity
# check below, to have the identical letter-adjacency defect as the four
# older digit-shape patterns -- "acct 12345678xyz" read as open, because a
# letter glued directly onto the digits is (as everywhere else in this
# module) not a word/non-word transition. The leading \b before the noun
# is a different thing entirely and stays: that boundary guards a WORD,
# which is exactly what \b is for (see the phrase markers below), and the
# noun alternation's own trailing guard (built into _ROUTING_NOUN /
# _ACCOUNT_NOUN above) is what keeps this pattern from matching mid-word.
_NOUN_DIRECT_DIGITS = re.compile(
    rf"\b(?:{_ROUTING_NOUN}|{_ACCOUNT_NOUN})\s*:?\s*\d{{4,}}", re.I)

# KNOWN, NOT FIXED: boundary-free \d{9,} was measured (20,000 simulated
# samples per shape) to flag 17.9% of random 40-character hex git SHAs and
# 13.5% of random UUIDs, against 0.00% with the \b bookends this module used
# to have -- base64 tokens are unaffected. There is no live corpus impact
# today (44 turns carry a hex-looking token >= 20 chars, none of which
# currently flags), but git_repos is a live source and this will degrade as
# more git history is ingested. Recorded here rather than fixed: no
# proposed fix was judged worth its own false-positive cost at review time.
#
# Every marker below is tagged with its boundary category, checked by
# test_classify.py's structural invariant test
# (test_no_digit_shape_marker_carries_a_boundary_bookend) rather than left
# as a comment for the next reviewer to re-discover by hand:
#
# * "digit": the ambiguous side is a digit run. \b cannot appear anywhere
#   in the pattern, because a letter or underscore is a word character
#   too, so \b\d{9,}\b cannot match "ID123456789" any more than \b can
#   mark where a digit run ends next to a letter with no space between
#   them. Enforced: zero occurrences of "\b" in the compiled source.
# * "word": the ambiguous side is a NOUN, and a noun mid-word is exactly
#   what \b is for -- "rerouting number", "subaccount number" and
#   "myaccount #123" must NOT match on substring alone. Exempt from the
#   "digit" rule; checked instead by the leading-\b tests further down in
#   test_classify.py (test_rerouting_number_stays_open and siblings).
_MARKERS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(rf"\d{{3}}{_SEP}\d{{2}}{_SEP}\d{{4}}"), "digit"),      # SSN, separated
    (re.compile(rf"\d{{2}}{_SEP}\d{{7}}"), "digit"),                  # EIN, separated
    (re.compile(r"\d{9,}"), "digit"),                # bare digit run, unbounded above, unbounded adjacency
    (re.compile(rf"\d{{4}}{_SEP}\d{{4}}{_SEP}\d{{4}}(?:{_SEP}\d{{1,4}})?"), "digit"),  # grouped account/card
    (re.compile(rf"\b{_ROUTING_NOUN}\s*{_QUALIFIER}", re.I), "word"),
    # "account" alone missed the common CPA-office abbreviations "acct" and
    # "a/c" (e.g. "acct #12345678"). Deliberately NOT including bare "act":
    # this is a tax practice's data, where "the Act" (Tax Cuts and Jobs Act,
    # CARES Act, ...) and "Act #<form/section>" are ordinary domain
    # vocabulary, not account references -- adding it would trade a content
    # false-negative for a source-of-truth false-positive on real
    # discussion of legislation, not close the hole it's meant to close.
    (re.compile(rf"\b{_ACCOUNT_NOUN}\s*{_QUALIFIER}", re.I), "word"),
    (_NOUN_DIRECT_DIGITS, "word"),
]

# Unicode characters that behave like an ASCII separator but are not one,
# handled as two FAMILIES rather than as a list of the specific codepoints a
# review happened to demonstrate -- a prior version of this table named only
# U+00A0 and U+2011 and was found, the next time it was reviewed, to have
# left every other member of both families unswept:
#
# * Cf (Format): zero-width joiners and soft hyphen. These render as
#   invisible, so the honest normalization is to remove them, not to
#   substitute a visible character -- "123​45​6789" is meant to be
#   read as one contiguous number with an invisible seam, not as
#   hyphen-separated.
# * Pd (Dash Punctuation): every dash variant -- en dash, em dash, figure
#   dash, horizontal bar, hyphen, non-breaking hyphen, and the fullwidth and
#   small compatibility forms -- folds to ASCII '-'. NFKC alone does not
#   reach this family: it maps U+2011 (non-breaking hyphen) to U+2010
#   (hyphen), not to U+002D, so the target of that mapping needs handling in
#   its own right, which the Pd sweep below gives it for free.
# * MINUS SIGN (U+2212) behaves like a dash but Unicode categorizes it as Sm
#   (Math Symbol), a category far too broad to sweep wholesale -- it also
#   contains '+', '=', '<', '>', which must never fold to '-'. Named
#   individually for that reason; this is the one deliberate exception to
#   "handle the category, not the character."
_DASH_LOOKALIKE = "−"  # MINUS SIGN — category Sm, not Pd; see above


def _for_matching(text: str) -> str:
    """A normalized VIEW of `text` used only to decide whether a marker
    fires -- never stored, never returned, and the caller's Turn is
    unmodified (it is frozen, so there is no way to mutate it in place).

    NFKC runs first and remains load-bearing on its own: it is what maps a
    non-breaking space and every other Unicode space variant to ASCII
    space, and U+2011 to U+2010, before the category sweep below ever sees
    them. The sweep after it folds the dash family to '-' and drops the
    invisible-format family entirely, neither of which NFKC reaches on its
    own (see the module-level comment above the two categories).
    """
    normalized = unicodedata.normalize("NFKC", text)
    out = []
    for ch in normalized:
        category = unicodedata.category(ch)
        if category == "Cf":
            continue
        if category == "Pd" or ch == _DASH_LOOKALIKE:
            out.append("-")
            continue
        out.append(ch)
    return "".join(out)


def classify(turn: Turn) -> str:
    """Client data is confidential; the subject's domain knowledge is not (spec §1, C1).

    Two independent routes to "confidential", either sufficient on its own:
    source (any turn from CONFIDENTIAL_SOURCES, regardless of content) and
    content markers (SSN/EIN/account-number patterns, regardless of source).
    The account-number marker (\\d{9,}) is intentionally broad — see
    task-16-report.md for what it does to ordinary numbers (years, phone
    numbers, timestamps) and why that breadth is accepted rather than tuned
    away: a false "confidential" only costs a little corpus fidelity, while a
    false "open" leaks a third party's regulated financial data into a
    corpus that may reach a hosted model. The two costs are not symmetric,
    so this classifier errs toward "confidential" wherever a pattern's
    breadth is a judgement call.

    This remains an enumerated set of known shapes and phrases, not a
    deny-by-default classifier like secrets.py's entropy fallback: an
    identifier of a shape none of these markers anticipates is still missed.
    That residual risk is accepted and tracked, not silently designed away.
    """
    if not isinstance(turn.text, str):
        raise ClassifyError(f"expected str for turn.text, got {type(turn.text).__name__}")
    if _is_confidential_source(turn.source):
        return "confidential"
    text = _for_matching(turn.text)
    if any(pattern.search(text) for pattern, _category in _MARKERS):
        return "confidential"
    return "open"


def is_exportable(turn: Turn) -> bool:
    return classify(turn) == "open"
